# Parameter-efficient training: freezes all FastESM parameters except multimer_attn
# Trains only ~0.5% of total parameters
# Pretrained weights auto-download from Synthyra HF Hub
# Recommended for quick experiments and prototyping

extends: ../base/8M.yaml

model:
  checkpoint: false
  copy_weights: false #true
  use_multimer: true

training:
  lr: 0.0008
  linear_decay: false #true  # uses paper's original linear decay
  use_erf_gelu: false #true  # uses paper's original erf gelu
  max_steps: 400000
  batch_size: 256  # larger batch possible due to activation checkpointing  --> 14.6 GB
  accumulate_grad: 1
  val_check_interval: 2000
  checkpoint_block_size: 0
  use_fused_multi_pathway: true
  use_compile: true  # torch.compile disabled by default (causes CUDA errors)
  

data:
  val_examples: 20000
  num_workers: 4
  crop_length: 512
  val_max_len: 1024
  data_dir: ./data/diamond

output:
  run_name: 8M_no_frozen
  checkpoint_every: 2000
