model:
  size: 35M
  use_multimer: true
  token_dropout: true
  checkpoint: ./ckpts/esm2_35M/pytorch_model.bin

training:
  max_steps: 200000
  batch_size: 16
  accumulate_grad: 4
  grad_clip: 1.0
  warmup_steps: 2000
  lr: 0.0001
  weight_decay: 0.01
  adam_betas: "[0.9, 0.98]"
  adam_eps: 1.0e-8
  end_learning_rate: 1.0e-5
  val_check_interval: 30000

data:
  split: filtered
  crop_length: 512
  val_examples: 250000
  data_dir: ./data
  max_examples: 0

output:
  run_name: 35M_base
  checkpoint_dir: ./ckpts
  checkpoint_every: 20000
  save_top_k: 1
